REST API
java-park-mail-ru/Brainstorm-09-2017 pull request #1
Opened 2017-09-20 00:38 UTC by kiryanenko

Написал регистрацию, авторизацию и т.д. Но возникла проблема, никак не получается установить сессию, т.е. вызываю `httpSession.setAttribute("userID", user.getId()); ` а толку ноль..., при чтении `httpSession.getAttribute("userId");` приходит null

2017-09-20 16:04 UTC, kiryanenko commented
Исправил, ошибка совсем глупая... Устанавливал "userID", а считывал из "userId"

2017-09-20 16:47 UTC, KSolovyev commented
добавьте, пожалуйста файлик .travis.yml и почините чекер

2017-09-20 16:48 UTC, KSolovyev commented
https://technopark-mail.slack.com/archives/C206Q4UKZ/p1505639870000026

2017-09-20 20:42 UTC, kiryanenko commented
Добавил

2017-09-21 09:30 UTC, KSolovyev requested changes

2017-09-21 09:30 UTC, KSolovyev commented on pom.xml
> +        <version>1.5.2.RELEASE</version>
1.5.7

2017-09-21 09:30 UTC, KSolovyev commented on src/main/java/application/controllers/UserController.java
> +            return ResponseEntity.badRequest().body(new ErrorResponse("Authorisation fail."));
typo: "Authorization failed"

2017-09-21 09:30 UTC, KSolovyev commented on src/main/java/application/models/User.java
> +        final String ePattern = "^([a-z0-9_-]+\\.)*[a-z0-9_-]+@[a-z0-9_-]+(\\.[a-z0-9_-]+)*\\.[a-z]{2,6}$";
тут очень много вариантов, вы не все проверили. Давайте проверять, что в центре есть "@" и посылать туда почту(когда-нибудь в далеком будущем)

2017-09-21 09:30 UTC, KSolovyev commented on src/main/java/application/models/User.java
> +    private Integer id;
id надо присваивать. Давайте сделаем
`private static final AtomicLong ID_GENERATOR = new AtomicLong();`

и будем раздавать новым пользователям id-шники. `ID_GENERATOR.getAndIncrement();`

2017-09-21 12:00 UTC, kiryanenko commented on src/main/java/application/models/User.java
> +    private Integer id;
Я так не сделал, потому что по идеи бд должна сама устанавливать id. Сейчас у меня сделано так, что в UserService.addUser добавляется пользователь в список users и устанавливается ему id = users.size - 1

2017-09-21 12:01 UTC, KSolovyev requested changes

2017-09-21 12:01 UTC, KSolovyev commented on pom.xml
> +            <version>1.5.2.RELEASE</version>
тут не нужны версии. Maven возьмет их из parent'a. А так может и сломаться что-нибудь

2017-09-21 12:14 UTC, KSolovyev commented on src/main/java/application/models/User.java
> +    private Integer id;
так нельзя делать. Будут многопоточные гонки, коллекция не потокобезопасная и счетчик будет сбиваться. Просто будет назначать одни и те же id для разных пользователей. Сделайте, как я советовал. Когда появится база, эта схема поменяется

2017-09-21 12:15 UTC, KSolovyev requested changes

2017-09-21 12:15 UTC, KSolovyev commented on src/main/java/application/services/UserService.java
> +public class UserService {
это должен быть спринговый сервис. Все статические методы и поля надо убрать. Добавить аннотацию @Service. И инжектить его в конструктор контроллера

2017-09-21 12:29 UTC, KSolovyev requested changes

2017-09-21 12:29 UTC, KSolovyev commented on BubbleRise.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Я просмотрел. Это мусорный файл, его не должно быть в проекте

2017-09-21 14:14 UTC, kiryanenko commented on src/main/java/application/services/UserService.java
> +public class UserService {
Переделал. Теперь вся бизнес-логика находится в UserService.

2017-09-21 14:15 UTC, kiryanenko commented on src/main/java/application/models/User.java
> +    private Integer id;
Сделал

2017-09-21 14:16 UTC, kiryanenko commented on BubbleRise.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Удалил

2017-09-25 13:27 UTC, KSolovyev requested changes

2017-09-25 13:27 UTC, KSolovyev commented on src/main/java/application/services/UserService.java
> +        final String error = user.loginValidator() + user.emailValidator() + user.passwordValidator();
давайте сделаем List, а не конкатинацию. Если уж хотите возвращать список ошибок

2017-09-25 13:27 UTC, KSolovyev commented on src/main/java/application/views/UserData.java
> +public class UserData {
UserData от User'a отличается только отсутствием поля с паролем. Если это так, то давайте в User на getPassword просто повесим аннотацию `@IgnoreJson` (или `@JsonIgnore`...), а этот класс удалим

2017-09-25 17:01 UTC, kiryanenko commented on src/main/java/application/services/UserService.java
> +        final String error = user.loginValidator() + user.emailValidator() + user.passwordValidator();
Переделал

2017-09-25 17:01 UTC, kiryanenko commented on src/main/java/application/views/UserData.java
> +public class UserData {
сделал

2017-09-26 11:06 UTC, KSolovyev requested changes
Делайте и давайте мержить

2017-09-26 11:06 UTC, KSolovyev commented on src/main/java/application/models/User.java
> +        return !Pattern.compile(ePattern).matcher(email).matches() ? new ErrorResponse(ErrorCode.NOT_VALID_EMAIL) : null;
`Pattern.compile` - надо вынести в константу. И, пожалуйста, аннотацию `@Nullable` наружу вытащите

2017-09-27 21:58 UTC, KSolovyev commented
Парни?

2017-09-28 00:44 UTC, kiryanenko commented on src/main/java/application/models/User.java
> +        return !Pattern.compile(ePattern).matcher(email).matches() ? new ErrorResponse(ErrorCode.NOT_VALID_EMAIL) : null;
Pattern.compile вынес.  Когда вытаскиваю @Nullable, ругается среда, требуя вернуть обратно

2017-10-04 10:46 UTC, KSolovyev requested changes

2017-10-04 10:46 UTC, KSolovyev commented on src/main/java/application/controllers/UsersController.java
> +        if (errors.isEmpty()) {
давайте сначала проверять на `if(!errors.isEmpty())` и сразу возвращать ответ. Так выглядит логичнее

2017-10-04 10:46 UTC, KSolovyev commented on src/main/java/application/models/User.java
> +public class User {
Класс нужно форматировать по конвенции. Не смотря на то, что он выглядит красиво, читать его сложнее, чем привычный код. Увы, но так никто не делает.

2017-10-04 10:46 UTC, KSolovyev commented on src/main/java/application/servicies/UsersService.java
> +    private static HashMap<Long, User> users = new HashMap<>();
поле не должно быть статическим

2017-10-04 10:46 UTC, KSolovyev commented on src/main/java/application/views/ErrorResponse.java
> +    public enum ErrorCode {
Можно вот так сделать
```
public enum ErrorCode {
   UNAUTHORIZED("User is unauthorized");

   private String msg;

   ErrorCode(String msg) {
        this.msg = msg;
   }

   public String getMsg() {
      return msg;
   }
}
```

2017-10-04 10:46 UTC, KSolovyev commented on src/main/java/application/servicies/UsersService.java
> +    public ArrayList<RecordResponse> getRecords() {
Здесь посортировать нужно пользователей, не модельку. В будущем за вас это будет делать база и код легко превратится в нормальный. Вместо компаратора можно использовать лямбду:
`users.sort((user1,user2) -> user1.getScore().compareTo(user2.getScore()))`

2017-10-04 10:46 UTC, KSolovyev commented on src/test/java/application/servicies/UsersServiceTest.java
> +public class UsersServiceTest {
Давайте тест в следующий пул реквест унесем. Сможете?

2017-10-04 16:04 UTC, kiryanenko commented on src/test/java/application/servicies/UsersServiceTest.java
> +public class UsersServiceTest {
Да, создал вторую ветку с тестами, а из этой их удалал

2017-10-04 21:08 UTC, KSolovyev requested changes

2017-10-04 21:08 UTC, KSolovyev commented on src/main/java/application/servicies/UsersService.java
> +        errors.add(credentials.emailValidator()).add(credentials.loginValidator()).add(credentials.passwordValidator());
будьте человеком(
```
 errors
    .add(credentials.emailValidator())
    .add(credentials.loginValidator())
    .add(credentials.passwordValidator())
```

2017-10-04 21:08 UTC, KSolovyev commented on src/main/java/application/views/ErrorResponseList.java
> +public class ErrorResponseList implements Iterable {
а чем вам просто List<ErrorResponse> не подошел? Вы же тоже самое написали, только меньше и хуже

2017-10-04 21:08 UTC, KSolovyev commented on src/main/java/application/views/ErrorResponse.java
> +        this.code = code.ordinal();
если уж хотите использовать числовой код ошибки, то добавьте его вторым параметром в enum. Если написать кастомный `... extends JsonSerializer<ErrorCode>`, то сделав `@JsonSerialize(using=...)` можно вообще от внешнего класса избавиться. Но это задание со звездочкой

2017-10-04 22:30 UTC, kiryanenko commented on src/main/java/application/servicies/UsersService.java
> +        errors.add(credentials.emailValidator()).add(credentials.loginValidator()).add(credentials.passwordValidator());
Ок)

2017-10-04 22:39 UTC, kiryanenko commented on src/main/java/application/views/ErrorResponseList.java
> +public class ErrorResponseList implements Iterable {
Мне нужно было добавить фильтр null при добавлении, чтоб не проверять каждый раз на не нулл. Потом, мне не нравилось писать ArrayList<ErrorResponse>. Ну и еще, прост хотелось на практике применить интерфейс Iterable)
Сейчас решил просто унаследоваться от ArrayList<ErrorResponse> и переопределить метод add

2017-10-04 22:48 UTC, kiryanenko commented on src/main/java/application/views/ErrorResponse.java
> +        this.code = code.ordinal();
Ок, добавил вторым параметром. Прост лень было писать для каждой ошибки свой код, так он автоматом по порядку следованию добавлялся

2017-10-08 09:14 UTC, KSolovyev requested changes
Вот как-то так надо

2017-10-08 09:14 UTC, KSolovyev commented on src/main/java/application/views/ErrorResponseList.java
> +    public ErrorResponseList add(@Nullable ErrorResponse err) {
Вот эту функцию тоже надо убрать

2017-10-08 09:14 UTC, KSolovyev commented on src/main/java/application/models/User.java
> +    public @Nullable ErrorResponse emailValidator() {
Здесь вместо @Nullable ErrorResponse сделаем `@NotNull Optional<ErrorResponse>`

2017-10-08 09:14 UTC, KSolovyev commented on src/main/java/application/models/User.java
> +        final Pattern pattern = Pattern.compile("^[.a-z0-9_-]+@[a-z0-9_.-]+\\.[a-z]{2,6}$");
все паттерны надо вынести в константы

2017-10-08 09:14 UTC, KSolovyev commented on src/main/java/application/models/User.java
> +        return !pattern.matcher(email).matches() ? new ErrorResponse(ErrorCode.NOT_VALID_EMAIL) : null;
```
if(!EMAIL_PATTERN.matcher(email).matches()) {
    return Optional.of(ErrorCode.NOT_VALID_EMAIL);
} else {
    return Optional.empty();
}
```

2017-10-08 09:14 UTC, KSolovyev commented on src/main/java/application/servicies/UsersService.java
> +                .add(credentials.emailValidator())
`credentials.emailValidator().ifPresent((error) -> errors.add(error))`

2017-10-08 09:14 UTC, KSolovyev commented on src/main/java/application/servicies/UsersService.java
> +        final ErrorResponseList errors = new ErrorResponseList();
`final List<ErrorCode> errors = new List<ErrorCode>()`

2017-10-08 09:14 UTC, KSolovyev commented on src/main/java/application/servicies/UsersService.java
> +            return errors.getList();
`new ErrorListResponse(errors.stream().map(errorCode -> new ErrorResponse(errorCode)))`

2017-10-08 17:35 UTC, KSolovyev requested changes

2017-10-08 17:35 UTC, KSolovyev commented on src/main/java/application/servicies/UsersService.java
> +            return new ArrayList<>(errors.stream().map(ErrorResponse::new).collect(Collectors.toList()));
вот тут можно без `new ArrayList<>(...)`
и так коллектор вернет список

2017-10-08 18:39 UTC, kiryanenko commented on src/main/java/application/servicies/UsersService.java
> +            return new ArrayList<>(errors.stream().map(ErrorResponse::new).collect(Collectors.toList()));
ок, сделал

2017-10-09 19:02 UTC, KSolovyev approved these changes

2017-10-09 19:02 UTC, merged

2017-10-09 19:03 UTC, KSolovyev commented
я сделал сквош коммитов. Вам надо будет сделать мерж мастера в девелоп