БД + Тесты
java-park-mail-ru/Brainstorm-09-2017 pull request #2
Opened 2017-10-16 22:55 UTC by kiryanenko

2017-10-17 17:30 UTC, Badya requested changes

2017-10-17 17:30 UTC, Badya commented on src/main/java/application/servicies/UsersService.java
> +        // Проверяю, что есть что-то на изменение
Комент излишен

2017-10-17 17:30 UTC, Badya commented on src/main/java/application/servicies/UsersService.java
> +            return new ArrayList<>();          // Возвращаяю пустой список ошибок
`Collections.EMPTY_LIST` и коммент точно станет не нужен

2017-10-17 17:30 UTC, Badya commented on src/main/java/application/servicies/UsersService.java
> +        if (count != 1) {
То есть если их вдруг 2 то все равно "не найден" ? =)

2017-10-17 17:30 UTC, Badya commented on src/main/java/application/servicies/UsersService.java
> +        final List<User> res = template.query("SELECT * FROM person WHERE id=:id LIMIT 1", params, USER_MAPPER);
А зачем LIMIT мы вроде полагаем что id уникален

2017-10-17 17:30 UTC, Badya commented on src/main/java/application/servicies/UsersService.java
> +                + "ORDER BY record DESC, number_of_games LIMIT 30", RECORD_MAPPER
Зачем хардкодить 30 игр, и почему 30?)

2017-10-17 17:30 UTC, Badya commented on src/main/java/application/servicies/UsersService.java
> +        template.update("TRUNCATE TABLE person CASCADE", new MapSqlParameterSource());
Очень смелый метод, еще и паблик, если сделан для тестов - то сужаем видимость до package-private, и тесты использующие это помещаем в тот-же пакет

2017-10-17 17:30 UTC, Badya commented on src/test/java/application/controllers/UsersControllerTest.java
> +        assert existingUser != null;
Есть же junit Assert

2017-10-17 17:30 UTC, Badya commented on src/test/java/application/models/UserTest.java
> +        notValidEmailTest("UpperCase@Mail.Ru");
Этот тест упадет на первой же ошибке не проверив все остальное - либо писать 7 тестов, либо делать `Parameterized` тест

2017-10-17 17:30 UTC, Badya commented on src/test/java/application/controllers/UsersControllerTest.java
> +        usersService.clearDB();
В @After наверное стоит чистить - "поел - убери за собой", можно оставить тут и добавить @After, или вообще написать org.junit.Rule

2017-10-17 17:30 UTC, Badya commented on src/main/java/application/servicies/UsersService.java
>  public class UsersService {
Все что тут работает с базой может бросать Exception

Пока что есть только DuplicateKeyException

2017-10-17 17:30 UTC, Badya commented on src/test/java/application/servicies/UsersServiceTest.java
> +    private UsersService usersService;
Если вынести базную работу из UserService - тогда в тестах базу можно будет подменить на программную реализацию или H2 - тестам не нужна будет реальная база

2017-10-17 19:36 UTC, kiryanenko commented on src/main/java/application/servicies/UsersService.java
> +            return new ArrayList<>();          // Возвращаяю пустой список ошибок
Комментарий не бывает лишним =) Тем более для фронтендера)))

2017-10-17 19:38 UTC, kiryanenko commented on src/main/java/application/servicies/UsersService.java
> +        // Проверяю, что есть что-то на изменение
Комментарий не бывает лишним =) Тем более для фронтендера

2017-10-17 19:41 UTC, kiryanenko commented on src/main/java/application/servicies/UsersService.java
> +        final List<User> res = template.query("SELECT * FROM person WHERE id=:id LIMIT 1", params, USER_MAPPER);
Ну ок) прост думал, что Бд будет быстрее

2017-10-18 19:47 UTC, kiryanenko commented on src/test/java/application/models/UserTest.java
> +        notValidEmailTest("UpperCase@Mail.Ru");
Ок, создал классы с Parameterized тестами: EmailValidatorTest, LoginValidatorTest, PasswordValidatorTest

2017-10-18 20:50 UTC, kiryanenko commented on src/test/java/application/servicies/UsersServiceTest.java
> +    private UsersService usersService;
Не очень понимаю, ведь так в тестах будут тестироваться запросы к бд. К тому же в UserService, по сути, находятся только эти запросы.

2017-10-19 10:51 UTC, Badya commented on src/test/java/application/servicies/UsersServiceTest.java
> +    private UsersService usersService;
Обсудили с коллегами - был не прав)

2017-10-19 10:55 UTC, Badya commented on src/main/java/application/servicies/UsersService.java
> +        // Проверяю, что есть что-то на изменение
На месте фронтендера я бы воспринял это как личное оскорбление)

2017-10-19 10:59 UTC, Badya commented
Тут есть коммиты с предыдущего ПР который уже в мастере - сделайте что-нибудь (merge/rebase) что бы этого не стало

2017-10-27 09:14 UTC, Badya requested changes

2017-10-27 09:14 UTC, Badya commented on src/main/java/application/controllers/UsersController.java
>          final Long userId = (Long) httpSession.getAttribute("userId");
Что будет если аттрибут вернет null, или если там будет не Long а мусор?
Написать тесты на это

2017-10-27 09:14 UTC, Badya commented
Трэвис починить

2017-10-28 16:53 UTC, KSolovyev commented
@kiryanenko Все дочинено?

2017-10-28 18:27 UTC, kiryanenko commented
@KSolovyev Теперь точно всё!

2017-11-13 08:32 UTC, merged